### PR TITLE
Deactivate project and add note to README

### PR DESCRIPTION
**Pull request by davehunt**
Pinging @bobsilverberg for review.

### CODE REVIEW

**Comment by davehunt** [comment]
Could I get a review from @mozilla/web-qa-sorcerers please?

**Comment by rbillings** [comment]
Maybe I missed it, but I don't see the changes to the readme file, all other changes look good.

**Comment by davehunt** [comment]
Thanks @rbillings, README changes included now. :smile:

**Comment by rbillings** [comment]
r+

**Pull request merged**
